from Abilities import * 

BattleAbilities = {'adaptability': {'name': 'Adaptability',
                  'num': 91,
                  'onModifyMove': adaptability.onModifyMove,
                  'rating': 4},
 'aerilate': {'name': 'Aerilate',
              'num': 184,
              'onBasePower': aerilate.onBasePower,
              'onBasePowerPriority': 23,
              'onModifyType': aerilate.onModifyType,
              'onModifyTypePriority': -1,
              'rating': 4},
 'aftermath': {'name': 'Aftermath',
               'num': 106,
               'onDamagingHit': aftermath.onDamagingHit,
               'onDamagingHitOrder': 1,
               'rating': 2.5},
 'airlock': {'name': 'Air Lock',
             'num': 76,
             'onStart': airlock.onStart,
             'onSwitchIn': airlock.onSwitchIn,
             'rating': 2,
             'suppressWeather': True},
 'analytic': {'name': 'Analytic',
              'num': 148,
              'onBasePower': analytic.onBasePower,
              'onBasePowerPriority': 21,
              'rating': 2.5},
 'angerpoint': {'name': 'Anger Point',
                'num': 83,
                'onHit': angerpoint.onHit,
                'rating': 1.5},
 'anticipation': {'name': 'Anticipation',
                  'num': 107,
                  'onStart': anticipation.onStart,
                  'rating': 0.5},
 'arenatrap': {'name': 'Arena Trap',
               'num': 71,
               'onFoeMaybeTrapPokemon': arenatrap.onFoeMaybeTrapPokemon,
               'onFoeTrapPokemon': arenatrap.onFoeTrapPokemon,
               'rating': 5},
 'aromaveil': {'isBreakable': True,
               'name': 'Aroma Veil',
               'num': 165,
               'onAllyTryAddVolatile': aromaveil.onAllyTryAddVolatile,
               'rating': 2},
 'asoneglastrier': {'isPermanent': True,
                    'name': 'As One (Glastrier)',
                    'num': 266,
                    'onEnd': asoneglastrier.onEnd,
                    'onFoeTryEatItem': asoneglastrier.onFoeTryEatItem,
                    'onPreStart': asoneglastrier.onPreStart,
                    'onSourceAfterFaint': asoneglastrier.onSourceAfterFaint,
                    'rating': 3.5},
 'asonespectrier': {'isPermanent': True,
                    'name': 'As One (Spectrier)',
                    'num': 267,
                    'onEnd': asonespectrier.onEnd,
                    'onFoeTryEatItem': asonespectrier.onFoeTryEatItem,
                    'onPreStart': asonespectrier.onPreStart,
                    'onSourceAfterFaint': asonespectrier.onSourceAfterFaint,
                    'rating': 3.5},
 'aurabreak': {'isBreakable': True,
               'name': 'Aura Break',
               'num': 188,
               'onAnyTryPrimaryHit': aurabreak.onAnyTryPrimaryHit,
               'onStart': aurabreak.onStart,
               'rating': 1},
 'baddreams': {'name': 'Bad Dreams',
               'num': 123,
               'onResidual': baddreams.onResidual,
               'onResidualOrder': 28,
               'onResidualSubOrder': 2,
               'rating': 1.5},
 'ballfetch': {'name': 'Ball Fetch', 'num': 237, 'rating': 0},
 'battery': {'name': 'Battery',
             'num': 217,
             'onAllyBasePower': battery.onAllyBasePower,
             'onAllyBasePowerPriority': 22,
             'rating': 0},
 'battlearmor': {'isBreakable': True,
                 'name': 'Battle Armor',
                 'num': 4,
                 'onCriticalHit': False,
                 'rating': 1},
 'battlebond': {'isPermanent': True,
                'name': 'Battle Bond',
                'num': 210,
                'onModifyMove': battlebond.onModifyMove,
                'onModifyMovePriority': -1,
                'onSourceAfterFaint': battlebond.onSourceAfterFaint,
                'rating': 4},
 'beastboost': {'name': 'Beast Boost',
                'num': 224,
                'onSourceAfterFaint': beastboost.onSourceAfterFaint,
                'rating': 3.5},
 'berserk': {'name': 'Berserk',
             'num': 201,
             'onAfterMoveSecondary': berserk.onAfterMoveSecondary,
             'onDamage': berserk.onDamage,
             'onTryEatItem': berserk.onTryEatItem,
             'rating': 2},
 'bigpecks': {'isBreakable': True,
              'name': 'Big Pecks',
              'num': 145,
              'onBoost': bigpecks.onBoost,
              'rating': 0.5},
 'blaze': {'name': 'Blaze',
           'num': 66,
           'onModifyAtk': blaze.onModifyAtk,
           'onModifyAtkPriority': 5,
           'onModifySpA': blaze.onModifySpA,
           'onModifySpAPriority': 5,
           'rating': 2},
 'bulletproof': {'isBreakable': True,
                 'name': 'Bulletproof',
                 'num': 171,
                 'onTryHit': bulletproof.onTryHit,
                 'rating': 3},
 'cheekpouch': {'name': 'Cheek Pouch',
                'num': 167,
                'onEatItem': cheekpouch.onEatItem,
                'rating': 2},
 'chillingneigh': {'name': 'Chilling Neigh',
                   'num': 264,
                   'onSourceAfterFaint': chillingneigh.onSourceAfterFaint,
                   'rating': 3},
 'chlorophyll': {'name': 'Chlorophyll',
                 'num': 34,
                 'onModifySpe': chlorophyll.onModifySpe,
                 'rating': 3},
 'clearbody': {'isBreakable': True,
               'name': 'Clear Body',
               'num': 29,
               'onBoost': clearbody.onBoost,
               'rating': 2},
 'cloudnine': {'name': 'Cloud Nine',
               'num': 13,
               'onStart': cloudnine.onStart,
               'onSwitchIn': cloudnine.onSwitchIn,
               'rating': 2,
               'suppressWeather': True},
 'colorchange': {'name': 'Color Change',
                 'num': 16,
                 'onAfterMoveSecondary': colorchange.onAfterMoveSecondary,
                 'rating': 0},
 'comatose': {'isPermanent': True,
              'name': 'Comatose',
              'num': 213,
              'onSetStatus': comatose.onSetStatus,
              'onStart': comatose.onStart,
              'rating': 4},
 'competitive': {'name': 'Competitive',
                 'num': 172,
                 'onAfterEachBoost': competitive.onAfterEachBoost,
                 'rating': 2.5},
 'compoundeyes': {'name': 'Compound Eyes',
                  'num': 14,
                  'onSourceModifyAccuracy': compoundeyes.onSourceModifyAccuracy,
                  'onSourceModifyAccuracyPriority': -1,
                  'rating': 3},
 'contrary': {'isBreakable': True,
              'name': 'Contrary',
              'num': 126,
              'onBoost': contrary.onBoost,
              'rating': 4.5},
 'corrosion': {'name': 'Corrosion', 'num': 212, 'rating': 2.5},
 'cottondown': {'name': 'Cotton Down',
                'num': 238,
                'onDamagingHit': cottondown.onDamagingHit,
                'rating': 2},
 'curiousmedicine': {'name': 'Curious Medicine',
                     'num': 261,
                     'onStart': curiousmedicine.onStart,
                     'rating': 0},
 'cursedbody': {'name': 'Cursed Body',
                'num': 130,
                'onDamagingHit': cursedbody.onDamagingHit,
                'rating': 2},
 'cutecharm': {'name': 'Cute Charm',
               'num': 56,
               'onDamagingHit': cutecharm.onDamagingHit,
               'rating': 0.5},
 'damp': {'isBreakable': True,
          'name': 'Damp',
          'num': 6,
          'onAnyDamage': damp.onAnyDamage,
          'onAnyTryMove': damp.onAnyTryMove,
          'rating': 1},
 'dancer': {'name': 'Dancer', 'num': 216, 'rating': 1.5},
 'darkaura': {'isBreakable': True,
              'name': 'Dark Aura',
              'num': 186,
              'onAnyBasePower': darkaura.onAnyBasePower,
              'onAnyBasePowerPriority': 20,
              'onStart': darkaura.onStart,
              'rating': 3},
 'dauntlessshield': {'name': 'Dauntless Shield',
                     'num': 235,
                     'onStart': dauntlessshield.onStart,
                     'rating': 3.5},
 'dazzling': {'isBreakable': True,
              'name': 'Dazzling',
              'num': 219,
              'onFoeTryMove': dazzling.onFoeTryMove,
              'rating': 2.5},
 'defeatist': {'name': 'Defeatist',
               'num': 129,
               'onModifyAtk': defeatist.onModifyAtk,
               'onModifyAtkPriority': 5,
               'onModifySpA': defeatist.onModifySpA,
               'onModifySpAPriority': 5,
               'rating': -1},
 'defiant': {'name': 'Defiant',
             'num': 128,
             'onAfterEachBoost': defiant.onAfterEachBoost,
             'rating': 2.5},
 'deltastream': {'name': 'Delta Stream',
                 'num': 191,
                 'onAnySetWeather': deltastream.onAnySetWeather,
                 'onEnd': deltastream.onEnd,
                 'onStart': deltastream.onStart,
                 'rating': 4},
 'desolateland': {'name': 'Desolate Land',
                  'num': 190,
                  'onAnySetWeather': desolateland.onAnySetWeather,
                  'onEnd': desolateland.onEnd,
                  'onStart': desolateland.onStart,
                  'rating': 4.5},
 'disguise': {'isBreakable': True,
              'isPermanent': True,
              'name': 'Disguise',
              'num': 209,
              'onCriticalHit': disguise.onCriticalHit,
              'onDamage': disguise.onDamage,
              'onDamagePriority': 1,
              'onEffectiveness': disguise.onEffectiveness,
              'onUpdate': disguise.onUpdate,
              'rating': 3.5},
 'download': {'name': 'Download',
              'num': 88,
              'onStart': download.onStart,
              'rating': 3.5},
 'dragonsmaw': {'name': "Dragon's Maw",
                'num': 263,
                'onModifyAtk': dragonsmaw.onModifyAtk,
                'onModifyAtkPriority': 5,
                'onModifySpA': dragonsmaw.onModifySpA,
                'onModifySpAPriority': 5,
                'rating': 3.5},
 'drizzle': {'name': 'Drizzle',
             'num': 2,
             'onStart': drizzle.onStart,
             'rating': 4},
 'drought': {'name': 'Drought',
             'num': 70,
             'onStart': drought.onStart,
             'rating': 4},
 'dryskin': {'isBreakable': True,
             'name': 'Dry Skin',
             'num': 87,
             'onFoeBasePower': dryskin.onFoeBasePower,
             'onFoeBasePowerPriority': 17,
             'onTryHit': dryskin.onTryHit,
             'onWeather': dryskin.onWeather,
             'rating': 3},
 'earlybird': {'name': 'Early Bird', 'num': 48, 'rating': 1.5},
 'effectspore': {'name': 'Effect Spore',
                 'num': 27,
                 'onDamagingHit': effectspore.onDamagingHit,
                 'rating': 2},
 'electricsurge': {'name': 'Electric Surge',
                   'num': 226,
                   'onStart': electricsurge.onStart,
                   'rating': 4},
 'emergencyexit': {'name': 'Emergency Exit',
                   'num': 194,
                   'onEmergencyExit': emergencyexit.onEmergencyExit,
                   'rating': 1},
 'fairyaura': {'isBreakable': True,
               'name': 'Fairy Aura',
               'num': 187,
               'onAnyBasePower': fairyaura.onAnyBasePower,
               'onAnyBasePowerPriority': 20,
               'onStart': fairyaura.onStart,
               'rating': 3},
 'filter': {'isBreakable': True,
            'name': 'Filter',
            'num': 111,
            'onSourceModifyDamage': filter.onSourceModifyDamage,
            'rating': 3},
 'flamebody': {'name': 'Flame Body',
               'num': 49,
               'onDamagingHit': flamebody.onDamagingHit,
               'rating': 2},
 'flareboost': {'name': 'Flare Boost',
                'num': 138,
                'onBasePower': flareboost.onBasePower,
                'onBasePowerPriority': 19,
                'rating': 2},
 'flashfire': {'condition': {'noCopy': True,
                          'onEnd': flashfire.onEnd,
                          'onModifyAtk': flashfire.onModifyAtk,
                          'onModifyAtkPriority': 5,
                          'onModifySpA': flashfire.onModifySpA,
                          'onModifySpAPriority': 5,
                          'onStart': flashfire.onStart},
               'isBreakable': True,
               'name': 'Flash Fire',
               'num': 18,
               'onEnd': flashfire.onEnd,
               'onTryHit': flashfire.onTryHit,
               'rating': 3.5},
 'flowergift': {'isBreakable': True,
                'name': 'Flower Gift',
                'num': 122,
                'onAllyModifyAtk': flowergift.onAllyModifyAtk,
                'onAllyModifyAtkPriority': 3,
                'onAllyModifySpD': flowergift.onAllyModifySpD,
                'onAllyModifySpDPriority': 4,
                'onStart': flowergift.onStart,
                'onUpdate': flowergift.onUpdate,
                'rating': 1},
 'flowerveil': {'isBreakable': True,
                'name': 'Flower Veil',
                'num': 166,
                'onAllyBoost': flowerveil.onAllyBoost,
                'onAllySetStatus': flowerveil.onAllySetStatus,
                'onAllyTryAddVolatile': flowerveil.onAllyTryAddVolatile,
                'rating': 0},
 'fluffy': {'isBreakable': True,
            'name': 'Fluffy',
            'num': 218,
            'onSourceModifyDamage': fluffy.onSourceModifyDamage,
            'rating': 3.5},
 'forecast': {'name': 'Forecast',
              'num': 59,
              'onUpdate': forecast.onUpdate,
              'rating': 2},
 'forewarn': {'name': 'Forewarn',
              'num': 108,
              'onStart': forewarn.onStart,
              'rating': 0.5},
 'friendguard': {'isBreakable': True,
                 'name': 'Friend Guard',
                 'num': 132,
                 'onAnyModifyDamage': friendguard.onAnyModifyDamage,
                 'rating': 0},
 'frisk': {'name': 'Frisk',
           'num': 119,
           'onStart': frisk.onStart,
           'rating': 1.5},
 'fullmetalbody': {'name': 'Full Metal Body',
                   'num': 230,
                   'onBoost': fullmetalbody.onBoost,
                   'rating': 2},
 'furcoat': {'isBreakable': True,
             'name': 'Fur Coat',
             'num': 169,
             'onModifyDef': furcoat.onModifyDef,
             'onModifyDefPriority': 6,
             'rating': 4},
 'galewings': {'name': 'Gale Wings',
               'num': 177,
               'onModifyPriority': galewings.onModifyPriority,
               'rating': 3},
 'galvanize': {'name': 'Galvanize',
               'num': 206,
               'onBasePower': galvanize.onBasePower,
               'onBasePowerPriority': 23,
               'onModifyType': galvanize.onModifyType,
               'onModifyTypePriority': -1,
               'rating': 4},
 'gluttony': {'name': 'Gluttony', 'num': 82, 'rating': 1.5},
 'gooey': {'name': 'Gooey',
           'num': 183,
           'onDamagingHit': gooey.onDamagingHit,
           'rating': 2},
 'gorillatactics': {'name': 'Gorilla Tactics',
                    'num': 255,
                    'onBeforeMove': gorillatactics.onBeforeMove,
                    'onDisableMove': gorillatactics.onDisableMove,
                    'onEnd': gorillatactics.onEnd,
                    'onModifyAtk': gorillatactics.onModifyAtk,
                    'onModifyAtkPriority': 1,
                    'onModifyMove': gorillatactics.onModifyMove,
                    'onStart': gorillatactics.onStart,
                    'rating': 4.5},
 'grasspelt': {'isBreakable': True,
               'name': 'Grass Pelt',
               'num': 179,
               'onModifyDef': grasspelt.onModifyDef,
               'onModifyDefPriority': 6,
               'rating': 0.5},
 'grassysurge': {'name': 'Grassy Surge',
                 'num': 229,
                 'onStart': grassysurge.onStart,
                 'rating': 4},
 'grimneigh': {'name': 'Grim Neigh',
               'num': 265,
               'onSourceAfterFaint': grimneigh.onSourceAfterFaint,
               'rating': 3},
 'gulpmissile': {'isPermanent': True,
                 'name': 'Gulp Missile',
                 'num': 241,
                 'onDamagingHit': gulpmissile.onDamagingHit,
                 'onSourceTryPrimaryHit': gulpmissile.onSourceTryPrimaryHit,
                 'rating': 2.5},
 'guts': {'name': 'Guts',
          'num': 62,
          'onModifyAtk': guts.onModifyAtk,
          'onModifyAtkPriority': 5,
          'rating': 3},
 'harvest': {'name': 'Harvest',
             'num': 139,
             'onResidual': harvest.onResidual,
             'onResidualOrder': 28,
             'onResidualSubOrder': 2,
             'rating': 2.5},
 'healer': {'name': 'Healer',
            'num': 131,
            'onResidual': healer.onResidual,
            'onResidualOrder': 5,
            'onResidualSubOrder': 3,
            'rating': 0},
 'heatproof': {'isBreakable': True,
               'name': 'Heatproof',
               'num': 85,
               'onDamage': heatproof.onDamage,
               'onSourceBasePower': heatproof.onSourceBasePower,
               'onSourceBasePowerPriority': 18,
               'rating': 2},
 'heavymetal': {'isBreakable': True,
                'name': 'Heavy Metal',
                'num': 134,
                'onModifyWeight': heavymetal.onModifyWeight,
                'onModifyWeightPriority': 1,
                'rating': 0},
 'honeygather': {'name': 'Honey Gather', 'num': 118, 'rating': 0},
 'hugepower': {'name': 'Huge Power',
               'num': 37,
               'onModifyAtk': hugepower.onModifyAtk,
               'onModifyAtkPriority': 5,
               'rating': 5},
 'hungerswitch': {'name': 'Hunger Switch',
                  'num': 258,
                  'onResidual': hungerswitch.onResidual,
                  'onResidualOrder': 29,
                  'rating': 1},
 'hustle': {'name': 'Hustle',
            'num': 55,
            'onModifyAtk': hustle.onModifyAtk,
            'onModifyAtkPriority': 5,
            'onSourceModifyAccuracy': hustle.onSourceModifyAccuracy,
            'onSourceModifyAccuracyPriority': -1,
            'rating': 3.5},
 'hydration': {'name': 'Hydration',
               'num': 93,
               'onResidual': hydration.onResidual,
               'onResidualOrder': 5,
               'onResidualSubOrder': 3,
               'rating': 1.5},
 'hypercutter': {'isBreakable': True,
                 'name': 'Hyper Cutter',
                 'num': 52,
                 'onBoost': hypercutter.onBoost,
                 'rating': 1.5},
 'icebody': {'name': 'Ice Body',
             'num': 115,
             'onImmunity': icebody.onImmunity,
             'onWeather': icebody.onWeather,
             'rating': 1},
 'iceface': {'isBreakable': True,
             'isPermanent': True,
             'name': 'Ice Face',
             'num': 248,
             'onAnyWeatherStart': iceface.onAnyWeatherStart,
             'onCriticalHit': iceface.onCriticalHit,
             'onDamage': iceface.onDamage,
             'onDamagePriority': 1,
             'onEffectiveness': iceface.onEffectiveness,
             'onStart': iceface.onStart,
             'onUpdate': iceface.onUpdate,
             'rating': 3},
 'icescales': {'isBreakable': True,
               'name': 'Ice Scales',
               'num': 246,
               'onSourceModifyDamage': icescales.onSourceModifyDamage,
               'rating': 4},
 'illuminate': {'name': 'Illuminate', 'num': 35, 'rating': 0},
 'illusion': {'name': 'Illusion',
              'num': 149,
              'onBeforeSwitchIn': illusion.onBeforeSwitchIn,
              'onDamagingHit': illusion.onDamagingHit,
              'onEnd': illusion.onEnd,
              'onFaint': illusion.onFaint,
              'rating': 4.5},
 'immunity': {'isBreakable': True,
              'name': 'Immunity',
              'num': 17,
              'onSetStatus': immunity.onSetStatus,
              'onUpdate': immunity.onUpdate,
              'rating': 2},
 'imposter': {'name': 'Imposter',
              'num': 150,
              'onStart': imposter.onStart,
              'onSwitchIn': imposter.onSwitchIn,
              'rating': 5},
 'infiltrator': {'name': 'Infiltrator',
                 'num': 151,
                 'onModifyMove': infiltrator.onModifyMove,
                 'rating': 2.5},
 'innardsout': {'name': 'Innards Out',
                'num': 215,
                'onDamagingHit': innardsout.onDamagingHit,
                'onDamagingHitOrder': 1,
                'rating': 4},
 'innerfocus': {'isBreakable': True,
                'name': 'Inner Focus',
                'num': 39,
                'onBoost': innerfocus.onBoost,
                'onTryAddVolatile': innerfocus.onTryAddVolatile,
                'rating': 1.5},
 'insomnia': {'isBreakable': True,
              'name': 'Insomnia',
              'num': 15,
              'onSetStatus': insomnia.onSetStatus,
              'onUpdate': insomnia.onUpdate,
              'rating': 2},
 'intimidate': {'name': 'Intimidate',
                'num': 22,
                'onStart': intimidate.onStart,
                'rating': 3.5},
 'intrepidsword': {'name': 'Intrepid Sword',
                   'num': 234,
                   'onStart': intrepidsword.onStart,
                   'rating': 4},
 'ironbarbs': {'name': 'Iron Barbs',
               'num': 160,
               'onDamagingHit': ironbarbs.onDamagingHit,
               'onDamagingHitOrder': 1,
               'rating': 2.5},
 'ironfist': {'name': 'Iron Fist',
              'num': 89,
              'onBasePower': ironfist.onBasePower,
              'onBasePowerPriority': 23,
              'rating': 3},
 'justified': {'name': 'Justified',
               'num': 154,
               'onDamagingHit': justified.onDamagingHit,
               'rating': 2.5},
 'keeneye': {'isBreakable': True,
             'name': 'Keen Eye',
             'num': 51,
             'onBoost': keeneye.onBoost,
             'onModifyMove': keeneye.onModifyMove,
             'rating': 0.5},
 'klutz': {'name': 'Klutz', 'num': 103, 'rating': -1},
 'leafguard': {'isBreakable': True,
               'name': 'Leaf Guard',
               'num': 102,
               'onSetStatus': leafguard.onSetStatus,
               'onTryAddVolatile': leafguard.onTryAddVolatile,
               'rating': 0.5},
 'levitate': {'isBreakable': True,
              'name': 'Levitate',
              'num': 26,
              'rating': 3.5},
 'libero': {'name': 'Libero',
            'num': 236,
            'onPrepareHit': libero.onPrepareHit,
            'rating': 4.5},
 'lightmetal': {'isBreakable': True,
                'name': 'Light Metal',
                'num': 135,
                'onModifyWeight': lightmetal.onModifyWeight,
                'rating': 1},
 'lightningrod': {'isBreakable': True,
                  'name': 'Lightning Rod',
                  'num': 31,
                  'onAnyRedirectTarget': lightningrod.onAnyRedirectTarget,
                  'onTryHit': lightningrod.onTryHit,
                  'rating': 3},
 'limber': {'isBreakable': True,
            'name': 'Limber',
            'num': 7,
            'onSetStatus': limber.onSetStatus,
            'onUpdate': limber.onUpdate,
            'rating': 2},
 'liquidooze': {'name': 'Liquid Ooze',
                'num': 64,
                'onSourceTryHeal': liquidooze.onSourceTryHeal,
                'rating': 1.5},
 'liquidvoice': {'name': 'Liquid Voice',
                 'num': 204,
                 'onModifyType': liquidvoice.onModifyType,
                 'onModifyTypePriority': -1,
                 'rating': 1.5},
 'longreach': {'name': 'Long Reach',
               'num': 203,
               'onModifyMove': longreach.onModifyMove,
               'rating': 1},
 'magicbounce': {'condition': {'duration': 1},
                 'isBreakable': True,
                 'name': 'Magic Bounce',
                 'num': 156,
                 'onAllyTryHitSide': magicbounce.onAllyTryHitSide,
                 'onTryHit': magicbounce.onTryHit,
                 'onTryHitPriority': 1,
                 'rating': 4},
 'magicguard': {'name': 'Magic Guard',
                'num': 98,
                'onDamage': magicguard.onDamage,
                'rating': 4},
 'magician': {'name': 'Magician',
              'num': 170,
              'onAfterMoveSecondarySelf': magician.onAfterMoveSecondarySelf,
              'rating': 1.5},
 'magmaarmor': {'isBreakable': True,
                'name': 'Magma Armor',
                'num': 40,
                'onImmunity': magmaarmor.onImmunity,
                'onUpdate': magmaarmor.onUpdate,
                'rating': 1},
 'magnetpull': {'name': 'Magnet Pull',
                'num': 42,
                'onFoeMaybeTrapPokemon': magnetpull.onFoeMaybeTrapPokemon,
                'onFoeTrapPokemon': magnetpull.onFoeTrapPokemon,
                'rating': 4},
 'marvelscale': {'isBreakable': True,
                 'name': 'Marvel Scale',
                 'num': 63,
                 'onModifyDef': marvelscale.onModifyDef,
                 'onModifyDefPriority': 6,
                 'rating': 2.5},
 'megalauncher': {'name': 'Mega Launcher',
                  'num': 178,
                  'onBasePower': megalauncher.onBasePower,
                  'onBasePowerPriority': 19,
                  'rating': 3},
 'merciless': {'name': 'Merciless',
               'num': 196,
               'onModifyCritRatio': merciless.onModifyCritRatio,
               'rating': 1.5},
 'mimicry': {'condition': {'onStart': mimicry.onStart,
                           'onUpdate': mimicry.onUpdate},
             'name': 'Mimicry',
             'num': 250,
             'onAnyTerrainStart': mimicry.onAnyTerrainStart,
             'onEnd': mimicry.onEnd,
             'onStart': mimicry.onStart,
             'rating': 0.5},
 'minus': {'name': 'Minus',
           'num': 58,
           'onModifySpA': minus.onModifySpA,
           'onModifySpAPriority': 5,
           'rating': 0},
 'mirrorarmor': {'isBreakable': True,
                 'name': 'Mirror Armor',
                 'num': 240,
                 'onBoost': mirrorarmor.onBoost,
                 'rating': 2},
 'mistysurge': {'name': 'Misty Surge',
                'num': 228,
                'onStart': mistysurge.onStart,
                'rating': 3.5},
 'moldbreaker': {'name': 'Mold Breaker',
                 'num': 104,
                 'onModifyMove': moldbreaker.onModifyMove,
                 'onStart': moldbreaker.onStart,
                 'rating': 3.5},
 'moody': {'name': 'Moody',
           'num': 141,
           'onResidual': moody.onResidual,
           'onResidualOrder': 28,
           'onResidualSubOrder': 2,
           'rating': 5},
 'motordrive': {'isBreakable': True,
                'name': 'Motor Drive',
                'num': 78,
                'onTryHit': motordrive.onTryHit,
                'rating': 3},
 'mountaineer': {'isBreakable': True,
                 'isNonstandard': 'CAP',
                 'name': 'Mountaineer',
                 'num': -2,
                 'onDamage': mountaineer.onDamage,
                 'onTryHit': mountaineer.onTryHit,
                 'rating': 3},
 'moxie': {'name': 'Moxie',
           'num': 153,
           'onSourceAfterFaint': moxie.onSourceAfterFaint,
           'rating': 3},
 'multiscale': {'isBreakable': True,
                'name': 'Multiscale',
                'num': 136,
                'onSourceModifyDamage': multiscale.onSourceModifyDamage,
                'rating': 3.5},
 'multitype': {'isPermanent': True,
               'name': 'Multitype',
               'num': 121,
               'rating': 4},
 'mummy': {'name': 'Mummy',
           'num': 152,
           'onDamagingHit': mummy.onDamagingHit,
           'rating': 2},
 'naturalcure': {'name': 'Natural Cure',
                 'num': 30,
                 'onCheckShow': naturalcure.onCheckShow,
                 'onSwitchOut': naturalcure.onSwitchOut,
                 'rating': 2.5},
 'neuroforce': {'name': 'Neuroforce',
                'num': 233,
                'onModifyDamage': neuroforce.onModifyDamage,
                'rating': 2.5},
 'neutralizinggas': {'name': 'Neutralizing Gas',
                     'num': 256,
                     'onEnd': neutralizinggas.onEnd,
                     'onPreStart': neutralizinggas.onPreStart,
                     'rating': 4},
 'noability': {'isNonstandard': 'Past',
               'name': 'No Ability',
               'num': 0,
               'rating': 0.1},
 'noguard': {'name': 'No Guard',
             'num': 99,
             'onAnyAccuracy': noguard.onAnyAccuracy,
             'onAnyInvulnerability': noguard.onAnyInvulnerability,
             'onAnyInvulnerabilityPriority': 1,
             'rating': 4},
 'normalize': {'name': 'Normalize',
               'num': 96,
               'onBasePower': normalize.onBasePower,
               'onBasePowerPriority': 23,
               'onModifyType': normalize.onModifyType,
               'onModifyTypePriority': 1,
               'rating': 0},
 'oblivious': {'isBreakable': True,
               'name': 'Oblivious',
               'num': 12,
               'onBoost': oblivious.onBoost,
               'onImmunity': oblivious.onImmunity,
               'onTryHit': oblivious.onTryHit,
               'onUpdate': oblivious.onUpdate,
               'rating': 1.5},
 'overcoat': {'isBreakable': True,
              'name': 'Overcoat',
              'num': 142,
              'onImmunity': overcoat.onImmunity,
              'onTryHit': overcoat.onTryHit,
              'onTryHitPriority': 1,
              'rating': 2},
 'overgrow': {'name': 'Overgrow',
              'num': 65,
              'onModifyAtk': overgrow.onModifyAtk,
              'onModifyAtkPriority': 5,
              'onModifySpA': overgrow.onModifySpA,
              'onModifySpAPriority': 5,
              'rating': 2},
 'owntempo': {'isBreakable': True,
              'name': 'Own Tempo',
              'num': 20,
              'onBoost': owntempo.onBoost,
              'onHit': owntempo.onHit,
              'onTryAddVolatile': owntempo.onTryAddVolatile,
              'onUpdate': owntempo.onUpdate,
              'rating': 1.5},
 'parentalbond': {'name': 'Parental Bond',
                  'num': 185,
                  'onPrepareHit': parentalbond.onPrepareHit,
                  'onSourceModifySecondaries': parentalbond.onSourceModifySecondaries,
                  'rating': 4.5},
 'pastelveil': {'isBreakable': True,
                'name': 'Pastel Veil',
                'num': 257,
                'onAllySetStatus': pastelveil.onAllySetStatus,
                'onAllySwitchIn': pastelveil.onAllySwitchIn,
                'onSetStatus': pastelveil.onSetStatus,
                'onStart': pastelveil.onStart,
                'onUpdate': pastelveil.onUpdate,
                'rating': 2},
 'perishbody': {'name': 'Perish Body',
                'num': 253,
                'onDamagingHit': perishbody.onDamagingHit,
                'rating': 1},
 'persistent': {'isNonstandard': 'CAP',
                'name': 'Persistent',
                'num': -4,
                'rating': 3},
 'pickpocket': {'name': 'Pickpocket',
                'num': 124,
                'onAfterMoveSecondary': pickpocket.onAfterMoveSecondary,
                'rating': 1},
 'pickup': {'name': 'Pickup',
            'num': 53,
            'onResidual': pickup.onResidual,
            'onResidualOrder': 28,
            'onResidualSubOrder': 2,
            'rating': 0.5},
 'pixilate': {'name': 'Pixilate',
              'num': 182,
              'onBasePower': pixilate.onBasePower,
              'onBasePowerPriority': 23,
              'onModifyType': pixilate.onModifyType,
              'onModifyTypePriority': -1,
              'rating': 4},
 'plus': {'name': 'Plus',
          'num': 57,
          'onModifySpA': plus.onModifySpA,
          'onModifySpAPriority': 5,
          'rating': 0},
 'poisonheal': {'name': 'Poison Heal',
                'num': 90,
                'onDamage': poisonheal.onDamage,
                'onDamagePriority': 1,
                'rating': 4},
 'poisonpoint': {'name': 'Poison Point',
                 'num': 38,
                 'onDamagingHit': poisonpoint.onDamagingHit,
                 'rating': 1.5},
 'poisontouch': {'name': 'Poison Touch',
                 'num': 143,
                 'onModifyMove': poisontouch.onModifyMove,
                 'rating': 2},
 'powerconstruct': {'isPermanent': True,
                    'name': 'Power Construct',
                    'num': 211,
                    'onResidual': powerconstruct.onResidual,
                    'onResidualOrder': 29,
                    'rating': 5},
 'powerofalchemy': {'name': 'Power of Alchemy',
                    'num': 223,
                    'onAllyFaint': powerofalchemy.onAllyFaint,
                    'rating': 0},
 'powerspot': {'name': 'Power Spot',
               'num': 249,
               'onAllyBasePower': powerspot.onAllyBasePower,
               'onAllyBasePowerPriority': 22,
               'rating': 1},
 'prankster': {'name': 'Prankster',
               'num': 158,
               'onModifyPriority': prankster.onModifyPriority,
               'rating': 4},
 'pressure': {'name': 'Pressure',
              'num': 46,
              'onDeductPP': pressure.onDeductPP,
              'onStart': pressure.onStart,
              'rating': 2.5},
 'primordialsea': {'name': 'Primordial Sea',
                   'num': 189,
                   'onAnySetWeather': primordialsea.onAnySetWeather,
                   'onEnd': primordialsea.onEnd,
                   'onStart': primordialsea.onStart,
                   'rating': 4.5},
 'prismarmor': {'name': 'Prism Armor',
                'num': 232,
                'onSourceModifyDamage': prismarmor.onSourceModifyDamage,
                'rating': 3},
 'propellertail': {'name': 'Propeller Tail',
                   'num': 239,
                   'onModifyMove': propellertail.onModifyMove,
                   'onModifyMovePriority': 1,
                   'rating': 0},
 'protean': {'name': 'Protean',
             'num': 168,
             'onPrepareHit': protean.onPrepareHit,
             'rating': 4.5},
 'psychicsurge': {'name': 'Psychic Surge',
                  'num': 227,
                  'onStart': psychicsurge.onStart,
                  'rating': 4},
 'punkrock': {'isBreakable': True,
              'name': 'Punk Rock',
              'num': 244,
              'onBasePower': punkrock.onBasePower,
              'onBasePowerPriority': 7,
              'onSourceModifyDamage': punkrock.onSourceModifyDamage,
              'rating': 3.5},
 'purepower': {'name': 'Pure Power',
               'num': 74,
               'onModifyAtk': purepower.onModifyAtk,
               'onModifyAtkPriority': 5,
               'rating': 5},
 'queenlymajesty': {'isBreakable': True,
                    'name': 'Queenly Majesty',
                    'num': 214,
                    'onFoeTryMove': queenlymajesty.onFoeTryMove,
                    'rating': 2.5},
 'quickdraw': {'name': 'Quick Draw',
               'num': 259,
               'onFractionalPriority': quickdraw.onFractionalPriority,
               'onFractionalPriorityPriority': -1,
               'rating': 2.5},
 'quickfeet': {'name': 'Quick Feet',
               'num': 95,
               'onModifySpe': quickfeet.onModifySpe,
               'rating': 2.5},
 'raindish': {'name': 'Rain Dish',
              'num': 44,
              'onWeather': raindish.onWeather,
              'rating': 1.5},
 'rattled': {'name': 'Rattled',
             'num': 155,
             'onAfterBoost': rattled.onAfterBoost,
             'onDamagingHit': rattled.onDamagingHit,
             'rating': 1.5},
 'rebound': {'condition': {'duration': 1},
             'isBreakable': True,
             'isNonstandard': 'CAP',
             'name': 'Rebound',
             'num': -3,
             'onAllyTryHitSide': rebound.onAllyTryHitSide,
             'onTryHit': rebound.onTryHit,
             'onTryHitPriority': 1,
             'rating': 3},
 'receiver': {'name': 'Receiver',
              'num': 222,
              'onAllyFaint': receiver.onAllyFaint,
              'rating': 0},
 'reckless': {'name': 'Reckless',
              'num': 120,
              'onBasePower': reckless.onBasePower,
              'onBasePowerPriority': 23,
              'rating': 3},
 'refrigerate': {'name': 'Refrigerate',
                 'num': 174,
                 'onBasePower': refrigerate.onBasePower,
                 'onBasePowerPriority': 23,
                 'onModifyType': refrigerate.onModifyType,
                 'onModifyTypePriority': -1,
                 'rating': 4},
 'regenerator': {'name': 'Regenerator',
                 'num': 144,
                 'onSwitchOut': regenerator.onSwitchOut,
                 'rating': 4.5},
 'ripen': {'name': 'Ripen',
           'num': 247,
           'onBoost': ripen.onBoost,
           'onEatItem': ripen.onEatItem,
           'onSourceModifyDamage': ripen.onSourceModifyDamage,
           'onSourceModifyDamagePriority': -1,
           'onTryEatItem': ripen.onTryEatItem,
           'onTryEatItemPriority': -1,
           'onTryHeal': ripen.onTryHeal,
           'rating': 2},
 'rivalry': {'name': 'Rivalry',
             'num': 79,
             'onBasePower': rivalry.onBasePower,
             'onBasePowerPriority': 24,
             'rating': 0},
 'rkssystem': {'isPermanent': True,
               'name': 'RKS System',
               'num': 225,
               'rating': 4},
 'rockhead': {'name': 'Rock Head',
              'num': 69,
              'onDamage': rockhead.onDamage,
              'rating': 3},
 'roughskin': {'name': 'Rough Skin',
               'num': 24,
               'onDamagingHit': roughskin.onDamagingHit,
               'onDamagingHitOrder': 1,
               'rating': 2.5},
 'runaway': {'name': 'Run Away', 'num': 50, 'rating': 0},
 'sandforce': {'name': 'Sand Force',
               'num': 159,
               'onBasePower': sandforce.onBasePower,
               'onBasePowerPriority': 21,
               'onImmunity': sandforce.onImmunity,
               'rating': 2},
 'sandrush': {'name': 'Sand Rush',
              'num': 146,
              'onImmunity': sandrush.onImmunity,
              'onModifySpe': sandrush.onModifySpe,
              'rating': 3},
 'sandspit': {'name': 'Sand Spit',
              'num': 245,
              'onDamagingHit': sandspit.onDamagingHit,
              'rating': 2},
 'sandstream': {'name': 'Sand Stream',
                'num': 45,
                'onStart': sandstream.onStart,
                'rating': 4},
 'sandveil': {'isBreakable': True,
              'name': 'Sand Veil',
              'num': 8,
              'onImmunity': sandveil.onImmunity,
              'onModifyAccuracy': sandveil.onModifyAccuracy,
              'onModifyAccuracyPriority': -1,
              'rating': 1.5},
 'sapsipper': {'isBreakable': True,
               'name': 'Sap Sipper',
               'num': 157,
               'onAllyTryHitSide': sapsipper.onAllyTryHitSide,
               'onTryHit': sapsipper.onTryHit,
               'onTryHitPriority': 1,
               'rating': 3},
 'schooling': {'isPermanent': True,
               'name': 'Schooling',
               'num': 208,
               'onResidual': schooling.onResidual,
               'onResidualOrder': 29,
               'onStart': schooling.onStart,
               'rating': 3},
 'scrappy': {'name': 'Scrappy',
             'num': 113,
             'onBoost': scrappy.onBoost,
             'onModifyMove': scrappy.onModifyMove,
             'onModifyMovePriority': -5,
             'rating': 3},
 'screencleaner': {'name': 'Screen Cleaner',
                   'num': 251,
                   'onStart': screencleaner.onStart,
                   'rating': 2},
 'serenegrace': {'name': 'Serene Grace',
                 'num': 32,
                 'onModifyMove': serenegrace.onModifyMove,
                 'onModifyMovePriority': -2,
                 'rating': 3.5},
 'shadowshield': {'name': 'Shadow Shield',
                  'num': 231,
                  'onSourceModifyDamage': shadowshield.onSourceModifyDamage,
                  'rating': 3.5},
 'shadowtag': {'name': 'Shadow Tag',
               'num': 23,
               'onFoeMaybeTrapPokemon': shadowtag.onFoeMaybeTrapPokemon,
               'onFoeTrapPokemon': shadowtag.onFoeTrapPokemon,
               'rating': 5},
 'shedskin': {'name': 'Shed Skin',
              'num': 61,
              'onResidual': shedskin.onResidual,
              'onResidualOrder': 5,
              'onResidualSubOrder': 3,
              'rating': 3},
 'sheerforce': {'name': 'Sheer Force',
                'num': 125,
                'onBasePower': sheerforce.onBasePower,
                'onBasePowerPriority': 21,
                'onModifyMove': sheerforce.onModifyMove,
                'rating': 3.5},
 'shellarmor': {'isBreakable': True,
                'name': 'Shell Armor',
                'num': 75,
                'onCriticalHit': False,
                'rating': 1},
 'shielddust': {'isBreakable': True,
                'name': 'Shield Dust',
                'num': 19,
                'onModifySecondaries': shielddust.onModifySecondaries,
                'rating': 2},
 'shieldsdown': {'isPermanent': True,
                 'name': 'Shields Down',
                 'num': 197,
                 'onResidual': shieldsdown.onResidual,
                 'onResidualOrder': 29,
                 'onSetStatus': shieldsdown.onSetStatus,
                 'onStart': shieldsdown.onStart,
                 'onTryAddVolatile': shieldsdown.onTryAddVolatile,
                 'rating': 3},
 'simple': {'isBreakable': True,
            'name': 'Simple',
            'num': 86,
            'onBoost': simple.onBoost,
            'rating': 4},
 'skilllink': {'name': 'Skill Link',
               'num': 92,
               'onModifyMove': skilllink.onModifyMove,
               'rating': 3},
 'slowstart': {'condition': {'duration': 5,
                          'onEnd': slowstart.onEnd,
                          'onModifyAtk': slowstart.onModifyAtk,
                          'onModifyAtkPriority': 5,
                          'onModifySpe': slowstart.onModifySpe,
                             'onResidualOrder': 28,
                             'onResidualSubOrder': 2,
                          'onStart': slowstart.onStart},
               'name': 'Slow Start',
               'num': 112,
               'onEnd': slowstart.onEnd,
               'onStart': slowstart.onStart,
               'rating': -1},
 'slushrush': {'name': 'Slush Rush',
               'num': 202,
               'onModifySpe': slushrush.onModifySpe,
               'rating': 3},
 'sniper': {'name': 'Sniper',
            'num': 97,
            'onModifyDamage': sniper.onModifyDamage,
            'rating': 2},
 'snowcloak': {'isBreakable': True,
               'name': 'Snow Cloak',
               'num': 81,
               'onImmunity': snowcloak.onImmunity,
               'onModifyAccuracy': snowcloak.onModifyAccuracy,
               'onModifyAccuracyPriority': -1,
               'rating': 1.5},
 'snowwarning': {'name': 'Snow Warning',
                 'num': 117,
                 'onStart': snowwarning.onStart,
                 'rating': 4},
 'solarpower': {'name': 'Solar Power',
                'num': 94,
                'onModifySpA': solarpower.onModifySpA,
                'onModifySpAPriority': 5,
                'onWeather': solarpower.onWeather,
                'rating': 2},
 'solidrock': {'isBreakable': True,
               'name': 'Solid Rock',
               'num': 116,
               'onSourceModifyDamage': solidrock.onSourceModifyDamage,
               'rating': 3},
 'soulheart': {'name': 'Soul-Heart',
               'num': 220,
               'onAnyFaint': soulheart.onAnyFaint,
               'onAnyFaintPriority': 1,
               'rating': 3.5},
 'soundproof': {'isBreakable': True,
                'name': 'Soundproof',
                'num': 43,
                'onAllyTryHitSide': soundproof.onAllyTryHitSide,
                'onTryHit': soundproof.onTryHit,
                'rating': 1.5},
 'speedboost': {'name': 'Speed Boost',
                'num': 3,
                'onResidual': speedboost.onResidual,
                'onResidualOrder': 28,
                'onResidualSubOrder': 2,
                'rating': 4.5},
 'stakeout': {'name': 'Stakeout',
              'num': 198,
              'onModifyAtk': stakeout.onModifyAtk,
              'onModifyAtkPriority': 5,
              'onModifySpA': stakeout.onModifySpA,
              'onModifySpAPriority': 5,
              'rating': 4.5},
 'stall': {'name': 'Stall',
           'num': 100,
           'onFractionalPriority': -0.1,
           'rating': -1},
 'stalwart': {'name': 'Stalwart',
              'num': 242,
              'onModifyMove': stalwart.onModifyMove,
              'onModifyMovePriority': 1,
              'rating': 0},
 'stamina': {'name': 'Stamina',
             'num': 192,
             'onDamagingHit': stamina.onDamagingHit,
             'rating': 3.5},
 'stancechange': {'isPermanent': True,
                  'name': 'Stance Change',
                  'num': 176,
                  'onModifyMove': stancechange.onModifyMove,
                  'onModifyMovePriority': 1,
                  'rating': 4},
 'static': {'name': 'Static',
            'num': 9,
            'onDamagingHit': static.onDamagingHit,
            'rating': 2},
 'steadfast': {'name': 'Steadfast',
               'num': 80,
               'onFlinch': steadfast.onFlinch,
               'rating': 1},
 'steamengine': {'name': 'Steam Engine',
                 'num': 243,
                 'onDamagingHit': steamengine.onDamagingHit,
                 'rating': 2},
 'steelworker': {'name': 'Steelworker',
                 'num': 200,
                 'onModifyAtk': steelworker.onModifyAtk,
                 'onModifyAtkPriority': 5,
                 'onModifySpA': steelworker.onModifySpA,
                 'onModifySpAPriority': 5,
                 'rating': 3.5},
 'steelyspirit': {'name': 'Steely Spirit',
                  'num': 252,
                  'onAllyBasePower': steelyspirit.onAllyBasePower,
                  'onAllyBasePowerPriority': 22,
                  'rating': 3.5},
 'stench': {'name': 'Stench',
            'num': 1,
            'onModifyMove': stench.onModifyMove,
            'onModifyMovePriority': -1,
            'rating': 0.5},
 'stickyhold': {'isBreakable': True,
                'name': 'Sticky Hold',
                'num': 60,
                'onTakeItem': stickyhold.onTakeItem,
                'rating': 2},
 'stormdrain': {'isBreakable': True,
                'name': 'Storm Drain',
                'num': 114,
                'onAnyRedirectTarget': stormdrain.onAnyRedirectTarget,
                'onTryHit': stormdrain.onTryHit,
                'rating': 3},
 'strongjaw': {'name': 'Strong Jaw',
               'num': 173,
               'onBasePower': strongjaw.onBasePower,
               'onBasePowerPriority': 19,
               'rating': 3},
 'sturdy': {'isBreakable': True,
            'name': 'Sturdy',
            'num': 5,
            'onDamage': sturdy.onDamage,
            'onDamagePriority': -30,
            'onTryHit': sturdy.onTryHit,
            'rating': 3},
 'suctioncups': {'isBreakable': True,
                 'name': 'Suction Cups',
                 'num': 21,
                 'onDragOut': suctioncups.onDragOut,
                 'onDragOutPriority': 1,
                 'rating': 1},
 'superluck': {'name': 'Super Luck',
               'num': 105,
               'onModifyCritRatio': superluck.onModifyCritRatio,
               'rating': 1.5},
 'surgesurfer': {'name': 'Surge Surfer',
                 'num': 207,
                 'onModifySpe': surgesurfer.onModifySpe,
                 'rating': 3},
 'swarm': {'name': 'Swarm',
           'num': 68,
           'onModifyAtk': swarm.onModifyAtk,
           'onModifyAtkPriority': 5,
           'onModifySpA': swarm.onModifySpA,
           'onModifySpAPriority': 5,
           'rating': 2},
 'sweetveil': {'isBreakable': True,
               'name': 'Sweet Veil',
               'num': 175,
               'onAllySetStatus': sweetveil.onAllySetStatus,
               'onAllyTryAddVolatile': sweetveil.onAllyTryAddVolatile,
               'rating': 2},
 'swiftswim': {'name': 'Swift Swim',
               'num': 33,
               'onModifySpe': swiftswim.onModifySpe,
               'rating': 3},
 'symbiosis': {'name': 'Symbiosis',
               'num': 180,
               'onAllyAfterUseItem': symbiosis.onAllyAfterUseItem,
               'rating': 0},
 'synchronize': {'name': 'Synchronize',
                 'num': 28,
                 'onAfterSetStatus': synchronize.onAfterSetStatus,
                 'rating': 2},
 'tangledfeet': {'isBreakable': True,
                 'name': 'Tangled Feet',
                 'num': 77,
                 'onModifyAccuracy': tangledfeet.onModifyAccuracy,
                 'onModifyAccuracyPriority': -1,
                 'rating': 1},
 'tanglinghair': {'name': 'Tangling Hair',
                  'num': 221,
                  'onDamagingHit': tanglinghair.onDamagingHit,
                  'rating': 2},
 'technician': {'name': 'Technician',
                'num': 101,
                'onBasePower': technician.onBasePower,
                'onBasePowerPriority': 30,
                'rating': 3.5},
 'telepathy': {'isBreakable': True,
               'name': 'Telepathy',
               'num': 140,
               'onTryHit': telepathy.onTryHit,
               'rating': 0},
 'teravolt': {'name': 'Teravolt',
              'num': 164,
              'onModifyMove': teravolt.onModifyMove,
              'onStart': teravolt.onStart,
              'rating': 3.5},
 'thickfat': {'isBreakable': True,
              'name': 'Thick Fat',
              'num': 47,
              'onSourceModifyAtk': thickfat.onSourceModifyAtk,
              'onSourceModifyAtkPriority': 6,
              'onSourceModifySpA': thickfat.onSourceModifySpA,
              'onSourceModifySpAPriority': 5,
              'rating': 3.5},
 'tintedlens': {'name': 'Tinted Lens',
                'num': 110,
                'onModifyDamage': tintedlens.onModifyDamage,
                'rating': 4},
 'torrent': {'name': 'Torrent',
             'num': 67,
             'onModifyAtk': torrent.onModifyAtk,
             'onModifyAtkPriority': 5,
             'onModifySpA': torrent.onModifySpA,
             'onModifySpAPriority': 5,
             'rating': 2},
 'toughclaws': {'name': 'Tough Claws',
                'num': 181,
                'onBasePower': toughclaws.onBasePower,
                'onBasePowerPriority': 21,
                'rating': 3.5},
 'toxicboost': {'name': 'Toxic Boost',
                'num': 137,
                'onBasePower': toxicboost.onBasePower,
                'onBasePowerPriority': 19,
                'rating': 2.5},
 'trace': {'name': 'Trace',
           'num': 36,
           'onStart': trace.onStart,
           'onUpdate': trace.onUpdate,
           'rating': 2.5},
 'transistor': {'name': 'Transistor',
                'num': 262,
                'onModifyAtk': transistor.onModifyAtk,
                'onModifyAtkPriority': 5,
                'onModifySpA': transistor.onModifySpA,
                'onModifySpAPriority': 5,
                'rating': 3.5},
 'triage': {'name': 'Triage',
            'num': 205,
            'onModifyPriority': triage.onModifyPriority,
            'rating': 3.5},
 'truant': {'condition': {},
            'name': 'Truant',
            'num': 54,
            'onBeforeMove': truant.onBeforeMove,
            'onBeforeMovePriority': 9,
            'onStart': truant.onStart,
            'rating': -1},
 'turboblaze': {'name': 'Turboblaze',
                'num': 163,
                'onModifyMove': turboblaze.onModifyMove,
                'onStart': turboblaze.onStart,
                'rating': 3.5},
 'unaware': {'isBreakable': True,
             'name': 'Unaware',
             'num': 109,
             'onAnyModifyBoost': unaware.onAnyModifyBoost,
             'rating': 4},
 'unburden': {'condition': {'onModifySpe': unburden.onModifySpe},
              'name': 'Unburden',
              'num': 84,
              'onAfterUseItem': unburden.onAfterUseItem,
              'onEnd': unburden.onEnd,
              'onTakeItem': unburden.onTakeItem,
              'rating': 3.5},
 'unnerve': {'name': 'Unnerve',
             'num': 127,
             'onEnd': unnerve.onEnd,
             'onFoeTryEatItem': unnerve.onFoeTryEatItem,
             'onPreStart': unnerve.onPreStart,
             'onStart': unnerve.onStart,
             'rating': 1.5},
 'unseenfist': {'name': 'Unseen Fist',
                'num': 260,
                'onModifyMove': unseenfist.onModifyMove,
                'rating': 2},
 'victorystar': {'name': 'Victory Star',
                 'num': 162,
                 'onAnyModifyAccuracy': victorystar.onAnyModifyAccuracy,
                 'onAnyModifyAccuracyPriority': -1,
                 'rating': 2},
 'vitalspirit': {'isBreakable': True,
                 'name': 'Vital Spirit',
                 'num': 72,
                 'onSetStatus': vitalspirit.onSetStatus,
                 'onUpdate': vitalspirit.onUpdate,
                 'rating': 2},
 'voltabsorb': {'isBreakable': True,
                'name': 'Volt Absorb',
                'num': 10,
                'onTryHit': voltabsorb.onTryHit,
                'rating': 3.5},
 'wanderingspirit': {'name': 'Wandering Spirit',
                     'num': 254,
                     'onDamagingHit': wanderingspirit.onDamagingHit,
                     'rating': 2.5},
 'waterabsorb': {'isBreakable': True,
                 'name': 'Water Absorb',
                 'num': 11,
                 'onTryHit': waterabsorb.onTryHit,
                 'rating': 3.5},
 'waterbubble': {'isBreakable': True,
                 'name': 'Water Bubble',
                 'num': 199,
                 'onModifyAtk': waterbubble.onModifyAtk,
                 'onModifySpA': waterbubble.onModifySpA,
                 'onSetStatus': waterbubble.onSetStatus,
                 'onSourceModifyAtk': waterbubble.onSourceModifyAtk,
                 'onSourceModifyAtkPriority': 5,
                 'onSourceModifySpA': waterbubble.onSourceModifySpA,
                 'onSourceModifySpAPriority': 5,
                 'onUpdate': waterbubble.onUpdate,
                 'rating': 4.5},
 'watercompaction': {'name': 'Water Compaction',
                     'num': 195,
                     'onDamagingHit': watercompaction.onDamagingHit,
                     'rating': 1.5},
 'waterveil': {'isBreakable': True,
               'name': 'Water Veil',
               'num': 41,
               'onSetStatus': waterveil.onSetStatus,
               'onUpdate': waterveil.onUpdate,
               'rating': 2},
 'weakarmor': {'name': 'Weak Armor',
               'num': 133,
               'onDamagingHit': weakarmor.onDamagingHit,
               'rating': 1},
 'whitesmoke': {'isBreakable': True,
                'name': 'White Smoke',
                'num': 73,
                'onBoost': whitesmoke.onBoost,
                'rating': 2},
 'wimpout': {'name': 'Wimp Out',
             'num': 193,
             'onEmergencyExit': wimpout.onEmergencyExit,
             'rating': 1},
 'wonderguard': {'isBreakable': True,
                 'name': 'Wonder Guard',
                 'num': 25,
                 'onTryHit': wonderguard.onTryHit,
                 'rating': 5},
 'wonderskin': {'isBreakable': True,
                'name': 'Wonder Skin',
                'num': 147,
                'onModifyAccuracy': wonderskin.onModifyAccuracy,
                'onModifyAccuracyPriority': 10,
                'rating': 2},
 'zenmode': {'condition': {'onEnd': zenmode.onEnd,
                        'onStart': zenmode.onStart},
             'isPermanent': True,
             'name': 'Zen Mode',
             'num': 161,
             'onEnd': zenmode.onEnd,
             'onResidual': zenmode.onResidual,
             'onResidualOrder': 29,
             'rating': 0}}
